### PR TITLE
Adding maxLength attribute to all Form.Control elements

### LINKED ISSUE #163: Error message that the max character limit has been exceed
#157
We need to check that input fields haven't exceeded 1024 characters and should stop the user from updating/adding fields with that exceeded character amount.

### LINKED ISSUE #238: Create constants file
References user story #237 

add constants file

### PR DESCRIPTION
**Pull request by AshlynAdamson**
Closes #163 
Closes #238 

Technically, there's no error message, but instead I added a maxLength attribute to all Form.Control elements. That way a user can't even insert more than 1024 characters. This obviously easier, but if we want an error message or something similar I can get it added.

### CODE REVIEW

**Comment by roguedeleter** [comment]
Can we store this in a constant variable? I don't know if there already exists a constants.js file for the front end, but it would probably be easier to maintain over time to only have this variable in one place.

**Comment by AshlynAdamson** [comment]
I didn't add any tests for this because 1024 characters is a lot of have hard coded in the tests

> 

Good idea, I can get one added

**Comment by AshlynAdamson** [comment]
> Can we store this in a constant variable? I don't know if there already exists a constants.js file for the front end, but it would probably be easier to maintain over time to only have this variable in one place.

Good idea, I can get one created

**Comment by AshlynAdamson** [comment]
> > Can we store this in a constant variable? I don't know if there already exists a constants.js file for the front end, but it would probably be easier to maintain over time to only have this variable in one place.
> 
> Good idea, I can get one created

Constants file now added

**Review by roguedeleter — APPROVED** [review]

**Review by josephmoore99 — APPROVED** [review]

**Pull request merged**
