### PR TITLE
Add device type POST endpoint

### LINKED ISSUE #176: Add device type POST endpoint
#77
We need to have an endpoint that will be able to create new device types.

### PR DESCRIPTION
**Pull request by josephmoore99**
Closes #176

### CODE REVIEW

**Comment by thessbsu** [comment]
Should the merge "into" on this one be feature/s2?

**Comment by Kenny-Miller** [comment]
> Should the merge "into" on this one be feature/s2?

I though feature/s2 was just going to be used for the demo?

**Comment by thessbsu** [comment]
I had the exact opposite thought. Main would remain untouched and all sprint related dev was going into the "sprint 2" branch.

**Comment by josephmoore99** [comment]
> 

You are correct, I thought I had set it properly but it looks like I did not. It should be correct now.

**Review by roguedeleter — APPROVED** [review]

**Review by thessbsu — APPROVED** [review]

**Pull request merged**
